name: Deploy App

on:
  push:
    branches:
      - main
    paths:
      - "src/frontend/**"
      - "src/backend/**"
  workflow_dispatch:

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Login to Docker Hub
        run: echo "${{ secrets.DOCKER_PASSWORD }}" | docker login -u "${{ secrets.DOCKER_USERNAME }}" --password-stdin

      - name: Build & Push Backend Image
        run: |
          cd src/backend
          docker build -t ${{ secrets.DOCKER_USERNAME }}/yuyariy-backend:latest .
          docker push ${{ secrets.DOCKER_USERNAME }}/yuyariy-backend:latest

      - name: Build & Push Frontend Image
        run: |
          cd src/frontend
          docker build -t ${{ secrets.DOCKER_USERNAME }}/yuyariy-frontend:latest .
          docker push ${{ secrets.DOCKER_USERNAME }}/yuyariy-frontend:latest
